-- Generated by the database client.
CREATE TABLE customer_behavior(
    customer_id bigint,
    age bigint,
    gender text,
    item_purchased text,
    category text,
    purchase_amount bigint,
    location text,
    size text,
    color text,
    season text,
    review_rating double precision,
    subscription_status text,
    shipping_type text,
    discount_applied text,
    promo_code_used text,
    previous_purchases bigint,
    payment_method text,
    frequency_of_purchases text,
    age_group text,
    column_frequency bigint,
    purchase_frequency_days bigint
);

SELECT * FROM customer_behavior LIMIT 10;

-- Q1. What is the total revenue generated by male vs. female customers? | Comparing revenue across demographics
    SELECT gender, SUM(purchase_amount) AS total_revenue
    FROM customer_behavior
    GROUP BY gender;
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
    SELECT customer_id, purchase_amount
    FROM customer_behavior
    WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_behavior);
--Q2A. Average Purchase Amount
    SELECT AVG(purchase_amount) as avg_purchase_amount
    FROM customer_behavior;
--Q3. Which are the top 5 products with the highest average review rating?
    SELECT item_purchased,
    --AVG(review_rating):: decimal(10,1) AS average_rating below is also correct
    ROUND(AVG(review_rating::NUMERIC), 1) AS average_rating,
    COUNT(*) AS total_reviews
    FROM customer_behavior
    GROUP BY item_purchased
    ORDER BY average_rating DESC
    LIMIT 5;
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
    SELECT shipping_type,
    ROUND (AVG(purchase_amount::NUMERIC),1) AS average_purchase_amount,
        CASE 
            WHEN AVG(purchase_amount::NUMERIC) = MAX(AVG(purchase_amount::NUMERIC)) OVER() 
            THEN 'More-Focus'
            ELSE  ''
        END AS focus_status
    FROM customer_behavior
    WHERE shipping_type IN ('Standard', 'Express')
    GROUP BY shipping_type;
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
    SELECT subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount::NUMERIC),1) AS Average_Spend,
    SUM(purchase_amount) AS total_revenue
    FROM customer_behavior
    GROUP BY subscription_status
    ORDER BY total_revenue, Average_Spend DESC;
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
    SELECT item_purchased,
    ROUND(100* SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)::NUMERIC/COUNT(*),2) AS discount_percentage
    FROM customer_behavior
    GROUP BY item_purchased
    ORDER BY discount_percentage DESC    
    LIMIT 5;
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment
    WITH customer_type AS (
        SELECT customer_id,previous_purchases,
        CASE 
         WHEN previous_purchases = 1 THEN 'New'
	     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	   ELSE 'Loyal'
	END AS customer_segment
 FROM customer_behavior
)
SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
 GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category? (USING CTE AND WINDOW FUNCTION)
    WITH item_counts as (
        SELECT category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
        FROM customer_behavior
        GROUP BY category, item_purchased
    )
    SELECT item_rank, category, item_purchased, total_orders
    FROM item_counts
    WHERE item_rank <= 3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;